### PR TITLE
Added some more various mappings

### PR DESCRIPTION
**Pull request by VikeStep**
Sorted the classes in the jar from largest to smallest and got mappings for a couple of the largest classes. Also found the Items and Blocks class, so there are a whole lot of easy mappings to make in those classes for all the different items and blocks names.

### CODE REVIEW

**Comment by shadowfacts** [comment]
Great, thanks!

**Comment by shadowfacts** [comment]
Did you use 15w31a or 15w31b for these?

**Comment by VikeStep** [comment]
15w31b

**Comment by shadowfacts** [comment]
Excellent, that means the mappings haven't changed from 15w31a to 15w31b!

**Pull request merged**
